// Generated by CoffeeScript 1.8.0
(function() {

  main = function() {
    $(':text').each(function(index, el) {
      // テキスト入力
      if (el.id == 'title') {
        $(el).val('title' + $.now());
      } else if (el.className.indexOf('tel') != -1) {
        $(el).val('01-2345-6789');
      } else if (el.className.indexOf('lat') != -1) {
        $(el).val('35.6808586');
      } else if (el.className.indexOf('lng') != -1) {
        $(el).val('139.7669568');
      } else if (el.className.indexOf('shop-url') != -1) {
        $(el).val(el.placeholder);
      } else {
        $(el).val('sample' + Math.round( Math.random()*100 ));   
      }
    });
    $('textarea').val('sample sample sample sample');
  };

  main();

}).call(this);
